// Generated by view binder compiler. Do not edit!
package ti.cardscanner;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.camera.view.PreviewView;
import androidx.constraintlayout.widget.ConstraintLayout;
import ti.cardscanner.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.appcelerator.kroll.common.Log;


public final class FragmentRecognitionBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final PreviewView cameraPreview;

  @NonNull
  public final TextView succeedResultsTextView;
  private static final String LCAT = "FragmentRecognitionBinding";


  private FragmentRecognitionBinding(@NonNull ConstraintLayout rootView,
      @NonNull PreviewView cameraPreview,@NonNull TextView succeedResultsTextView) {
    this.rootView = rootView;
    this.cameraPreview = cameraPreview;
    this.succeedResultsTextView = succeedResultsTextView;
  }

  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentRecognitionBinding inflate(@NonNull LayoutInflater inflater) {
    Log.d(LCAT, "inside FragmentRecognitionBinding");

    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentRecognitionBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
        Log.d(LCAT, "inside FragmentRecognitionBinding attachToParent");

    View root = inflater.inflate(R.layout.fragment_recognition, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentRecognitionBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
            Log.d(LCAT, "inside FragmentRecognitionBinding bind");

    int id;
    missingId: {
      id = R.id.cameraPreview;
      PreviewView cameraPreview = rootView.findViewById(id);
      if (cameraPreview == null) {
        break missingId;
      }


      id = R.id.succeedResultsTextView;
      TextView succeedResultsTextView = rootView.findViewById(id);
      if (succeedResultsTextView == null) {
        break missingId;
      }


      return new FragmentRecognitionBinding((ConstraintLayout) rootView, cameraPreview, succeedResultsTextView);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
