/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.cardscanner;

import java.util.HashMap;
import java.util.List;
import android.Manifest;
import androidx.core.app.ActivityCompat;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollObject;
import org.appcelerator.titanium.util.TiConvert;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.annotation.SuppressLint;
import android.content.pm.PackageManager;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;

import org.appcelerator.titanium.util.TiActivityResultHandler;
import org.appcelerator.titanium.util.TiActivitySupport;
import org.appcelerator.titanium.util.TiIntentWrapper;
import java.util.Locale;


import android.annotation.SuppressLint;
import android.graphics.Bitmap;
import android.graphics.PointF;
import android.os.Bundle;
import android.os.Handler;
import android.util.Size;
import android.view.View;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.RelativeLayout;

import androidx.appcompat.app.AlertDialog;

import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentTransaction;
import androidx.fragment.app.FragmentActivity;

import org.appcelerator.titanium.proxy.TiViewProxy;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Color;
import android.view.LayoutInflater;
import android.content.res.Resources;
import androidx.constraintlayout.widget.ConstraintLayout;
import java.util.HashMap;



@Kroll.module(name="TiCardscanner", id="ti.cardscanner")
public class TiCardscannerModule extends KrollModule
{
	// Standard Debugging variables
	private static final String LCAT = "TiCardscannerModule";
	private static final boolean DBG = TiConfig.LOGD;
	private KrollFunction callback;

	private static TiCardscannerModule _instance;

	private TiViewProxy overlayViewProxy;

	private int resId_viewHolder;
	private int id_view;
	private LayoutInflater inflater;
	private Activity activity;

	public TiCardscannerModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		//Log.d(LCAT, "inside onAppCreate");
	}

	public static TiCardscannerModule getInstance()
	{
		return _instance;
	}

	public void fireCallback(KrollDict dict)
	{
		if (callback!=null){
			callback.call(getKrollObject(), dict);
		}
	}

	public TiViewProxy getOverlayView()
	{
		return overlayViewProxy;
	}
		
	@Kroll.method
	public void close(Object params) {
		//Log.e(LCAT, "finish");

		ActivityScan.getInstance().finish();
	}


	@Kroll.method
	public void torch() {
		//Log.e(LCAT, "torch");

		ActivityScan.getInstance().torch();
	}


	@SuppressWarnings("rawtypes")
	@Kroll.method
	public void scan(Object params) {

		_instance = this;

		if (!(params instanceof HashMap)) {
			//Log.e(LCAT, "Argument for replaceAt must be a dictionary");
			return;
		}
		HashMap options = (HashMap) params;

		activity = TiApplication.getAppCurrentActivity();

		final String packageName = activity.getPackageName();
      	final Resources resources = activity.getResources();
		inflater = LayoutInflater.from(activity);

		//Create Intent and Launch
		Intent intent = new Intent(activity, ActivityScan.class);


		if (options.containsKey("callback")) {
			callback =(KrollFunction) options.get("callback");
		}
		if (options.containsKey("overlayView")) {
			//Log.e(LCAT, "++++++++++++++++  overlayView");

			overlayViewProxy = (TiViewProxy) options.get("overlayView");		
		}

		activity.startActivity(intent);
	}

}

